name: enet-keras
channels:
- !!python/unicode
  'defaults'
dependencies:
- !!python/unicode
  'openssl=1.0.2k=1'
- !!python/unicode
  'pip=9.0.1=py27_1'
- !!python/unicode
  'python=2.7.13=0'
- !!python/unicode
  'readline=6.2=2'
- !!python/unicode
  'setuptools=27.2.0=py27_0'
- !!python/unicode
  'sqlite=3.13.0=0'
- !!python/unicode
  'tk=8.5.18=0'
- !!python/unicode
  'wheel=0.29.0=py27_0'
- !!python/unicode
  'zlib=1.2.8=3'
- pip:
  - cycler==0.10.0
  - decorator==4.0.11
  - funcsigs==1.0.2
  - functools32==3.2.3.post2
  - h5py==2.7.0
  - keras==2.0.2
  - matplotlib==2.0.0
  - mock==2.0.0
  - networkx==1.11
  - numpy==1.12.1
  - olefile==0.44
  - opencv-python==3.2.0.7
  - pbr==3.0.0
  - pillow==4.1.0
  - protobuf==3.3.0
  - pyparsing==2.2.0
  - python-dateutil==2.6.0
  - pytz==2017.2
  - pywavelets==0.5.2
  - pyyaml==3.12
  - scikit-image==0.13.0
  - scipy==0.19.0
  - six==1.10.0
  - subprocess32==3.2.7
  - tensorflow-gpu==1.1.0
  - theano==0.9.0

